=== verdet23/verdet23/data/schema/icao.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/icao.json",
  "title": "Root",
  "type": "array",
  "default": [],
  "items": {
    "$id": "#root/items",
    "title": "Items",
    "type": "object",
    "required": [
      "icao",
      "type",
      "name",
      "lat",
      "long"
    ],
    "properties": {
      "icao": {
        "$id": "#root/items/icao",
        "title": "ICAO airport code",
        "type": "string",
        "default": "",
        "examples": [
          "PANC"
        ],
        "pattern": "^.*$"
      },
      "type": {
        "$id": "#root/items/type",
        "title": "Type",
        "type": "string",
        "default": "",
        "enum": [
          "large_airport",
          "medium_airport",
          "small_airport",
          "seaplane_base",
          "heliport",
          "closed"
        ]
      },
      "name": {
        "$id": "#root/items/name",
        "title": "Airport name",
        "type": "string",
        "default": "",
        "examples": [
          "Ted Stevens Anchorage International Airport"
        ],
        "pattern": "^.*$"
      },
      "lat": {
        "$id": "#root/items/lat",
        "title": "Latitude",
        "type": "number",
        "minimum": -90,
        "maximum": 90,
        "examples": [
          61.1744
        ]
      },
      "long": {
        "$id": "#root/items/long",
        "title": "Longitude",
        "type": "number",
        "minimum": -180,
        "maximum": 180,
        "examples": [
          -149.996002
        ]
      }
    }
  }
}

=== verdet23/verdet23/data/icao.json
[{"icao":"PAKD","type":"small_airport","name":"Kodiak Municipal Airport","lat":57.8059005737,"long":-152.37399292},{"icao":"PADQ","type":"medium_airport","name":"Kodiak Airport","lat":57.75,"long":-152.4940033},{"icao":"9Z3","type":"seaplane_base","name":"Kodiak \/Lilly Lake\/ Seaplane Base","lat":57.802600860596,"long":-152.38299560547},{"icao":"PANC","type":"large_airport","name":"Ted Stevens Anchorage International Airport","lat":61.1744,"long":-149.996002},{"icao":"PALH","type":"seaplane_base","name":"Lake Hood Airport","lat":61.18,"long":-149.972003},{"icao":"Z41","type":"small_airport","name":"Lake Hood Airport","lat":61.186946,"long":-149.965442},{"icao":"CYUL","type":"large_airport","name":"Montreal \/ Pierre Elliott Trudeau International Airport","lat":45.4706001282,"long":-73.7407989502},{"icao":"KRDU","type":"large_airport","name":"Raleigh Durham International Airport","lat":35.877601623535,"long":-78.787498474121},{"icao":"EGPE","type":"medium_airport","name":"Inverness Airport","lat":57.542499542236,"long":-4.0475001335144},{"icao":"EPKK","type":"large_airport","name":"Krak\u00f3w John Paul II International Airport","lat":50.077702,"long":19.7848},{"icao":"NVSW","type":"small_airport","name":"Walaha Airport","lat":-15.4119997025,"long":167.690994263},{"icao":"EDMV","type":"small_airport","name":"Vilshofen Airfield","lat":48.634998,"long":13.195556},{"icao":"EDMS","type":"small_airport","name":"Straubing Airport","lat":48.900833129883,"long":12.516667366028},{"icao":"EDDG","type":"medium_airport","name":"M\u00fcnster Osnabr\u00fcck Airport","lat":52.134602,"long":7.68483},{"icao":"EGLC","type":"medium_airport","name":"London City Airport","lat":51.505299,"long":0.055278},{"icao":"MWCR","type":"large_airport","name":"Owen Roberts International Airport","lat":19.2928009033,"long":-81.3576965332},{"icao":"EDQH","type":"small_airport","name":"Herzogenaurach Airport","lat":49.582500457764,"long":10.87805557251},{"icao":"EDMJ","type":"small_airport","name":"Flugplatz Jesenwang","lat":48.174168,"long":11.125},{"icao":"EDVU","type":"small_airport","name":"Flugplatz Uelzen","lat":52.983891,"long":10.465},{"icao":"EDNM","type":"small_airport","name":"Nittenau-Bruck Airport","lat":49.222499847412,"long":12.296667098999},{"icao":"EDDL","type":"large_airport","name":"D\u00fcsseldorf Airport","lat":51.289501,"long":6.76678},{"icao":"PASY","type":"medium_airport","name":"Eareckson Air Station","lat":52.71229935,"long":174.1139984},{"icao":"GEML","type":"medium_airport","name":"Melilla Airport","lat":35.2798,"long":-2.95626},{"icao":"PHNL","type":"large_airport","name":"Daniel K Inouye International Airport","lat":21.32062,"long":-157.924228},{"icao":"LIPI","type":"medium_airport","name":"Rivolto Air Base","lat":45.978699,"long":13.0493},{"icao":"LPPD","type":"large_airport","name":"Jo\u00e3o Paulo II Airport","lat":37.7411994934,"long":-25.6979007721},{"icao":"LIRF","type":"large_airport","name":"Rome\u2013Fiumicino Leonardo da Vinci International Airport","lat":41.804532,"long":12.251998},{"icao":"EPCD","type":"small_airport","name":"Depu\u0142tycze Kr\u00f3lewskie Airport","lat":51.082067,"long":23.437014},{"icao":"CYTZ","type":"medium_airport","name":"Billy Bishop Toronto City Centre Airport","lat":43.627499,"long":-79.396202},{"icao":"KRBL","type":"medium_airport","name":"Red Bluff Municipal Airport","lat":40.1506996155,"long":-122.251998901},{"icao":"ESSV","type":"medium_airport","name":"Visby Airport","lat":57.662799835205,"long":18.346200942993},{"icao":"ESSP","type":"medium_airport","name":"Norrk\u00f6ping Airport","lat":58.58629989624,"long":16.250600814819},{"icao":"ESMQ","type":"medium_airport","name":"Kalmar Airport","lat":56.685501,"long":16.2876},{"icao":"LOXT","type":"small_airport","name":"Brumowski  Air Base","lat":48.319247,"long":16.114016},{"icao":"YBEB","type":"small_airport","name":"Bellburn Airstrip","lat":-17.545,"long":128.305},{"icao":"ESSL","type":"medium_airport","name":"Link\u00f6ping City Airport","lat":58.4062004089,"long":15.6805000305},{"icao":"LSZH","type":"large_airport","name":"Z\u00fcrich Airport","lat":47.458056,"long":8.548056},{"icao":"LOAA","type":"small_airport","name":"Ottenschlag Airport","lat":48.4189,"long":15.215661},{"icao":"LSZT","type":"small_airport","name":"Lommis Airfield","lat":47.524399,"long":9.00306},{"icao":"LFMX","type":"small_airport","name":"A\u00e9rodrome de Ch\u00e2teau-Arnoux - Saint-Auban","lat":44.060001,"long":5.99139},{"icao":"ZUDC","type":"medium_airport","name":"Daocheng Yading Airport","lat":29.323056,"long":100.053333},{"icao":"LEBB","type":"medium_airport","name":"Bilbao Airport","lat":43.301102,"long":-2.91061},{"icao":"ETNG","type":"medium_airport","name":"Geilenkirchen Air Base","lat":50.9608,"long":6.04242},{"icao":"KEDU","type":"small_airport","name":"University Airport","lat":38.53150177002,"long":-121.78600311279},{"icao":"YSSY","type":"large_airport","name":"Sydney Kingsford Smith International Airport","lat":-33.946098327637,"long":151.17700195312},{"icao":"EGPH","type":"large_airport","name":"Edinburgh Airport","lat":55.950145,"long":-3.372288},{"icao":"KIND","type":"large_airport","name":"Indianapolis International Airport","lat":39.7173,"long":-86.294403},{"icao":"KBVS","type":"small_airport","name":"Skagit Regional Airport","lat":48.4709014893,"long":-122.42099762},{"icao":"S88","type":"small_airport","name":"Skykomish State Airport","lat":47.710899353027,"long":-121.33899688721},{"icao":"27W","type":"small_airport","name":"Lake Wenatchee State Airport","lat":47.819400787354,"long":-120.7200012207},{"icao":"S86","type":"small_airport","name":"Sky Harbor Airport","lat":47.870700836182,"long":-121.79199981689},{"icao":"21W","type":"small_airport","name":"Ranger Creek State Airport","lat":47.012901,"long":-121.533997},{"icao":"ESOE","type":"medium_airport","name":"\u00d6rebro Airport","lat":59.223701477051,"long":15.038000106812},{"icao":"LIPA","type":"medium_airport","name":"Aviano Air Base","lat":46.031898,"long":12.596503},{"icao":"KBLI","type":"medium_airport","name":"Bellingham International Airport","lat":48.79280090332,"long":-122.53800201416},{"icao":"NZKM","type":"small_airport","name":"Karamea Airport","lat":-41.236698150635,"long":172.10499572754},{"icao":"EDNU","type":"small_airport","name":"Thannhausen Airport","lat":48.290001,"long":10.441944},{"icao":"ESGJ","type":"medium_airport","name":"J\u00f6nk\u00f6ping Airport","lat":57.757598876953,"long":14.068699836731},{"icao":"ESOW","type":"medium_airport","name":"Stockholm V\u00e4ster\u00e5s Airport","lat":59.589401245117,"long":16.633600234985},{"icao":"WBGG","type":"medium_airport","name":"Kuching International Airport","lat":1.4846999645233,"long":110.34700012207},{"icao":"WBGR","type":"medium_airport","name":"Miri Airport","lat":4.3220100402832,"long":113.98699951172},{"icao":"ZZZZ","type":"small_airport","name":"Satsuma I\u014djima Airport","lat":30.784722,"long":130.270556},{"icao":"LEBL","type":"large_airport","name":"Josep Tarradellas Barcelona-El Prat Airport","lat":41.2971,"long":2.07846},{"icao":"CSB3","type":"small_airport","name":"St-Mathieu-De-Beloeil Airport","lat":45.590000152588,"long":-73.23860168457},{"icao":"EFMA","type":"medium_airport","name":"Mariehamn Airport","lat":60.1222,"long":19.898199},{"icao":"LIBD","type":"medium_airport","name":"Bari Karol Wojty\u0142a Airport","lat":41.138901,"long":16.760599},{"icao":"ESNZ","type":"medium_airport","name":"\u00c5re \u00d6stersund Airport","lat":63.194400787354,"long":14.50030040741},{"icao":"EHND","type":"small_airport","name":"Vliegveld Numansdorp","lat":51.7530556,"long":4.4552778},{"icao":"PMDY","type":"medium_airport","name":"Henderson Field","lat":28.201700210571,"long":-177.3809967041},{"icao":"EGHT","type":"heliport","name":"Tresco Heliport","lat":49.945598602295,"long":-6.3313899040222},{"icao":"EHDP","type":"medium_airport","name":"De Peel Air Base","lat":51.5172996521,"long":5.8557200431824},{"icao":"LSMP","type":"medium_airport","name":"Payerne Air Base","lat":46.8432,"long":6.91506004333},{"icao":"ENNK","type":"closed","name":"Narvik Framnes Airport","lat":68.436897,"long":17.3867},{"icao":"LG54","type":"small_airport","name":"Tympaki Airport","lat":35.063702,"long":24.767401},{"icao":"EPZA","type":"small_airport","name":"Zamo\u015b\u0107-Mokre Airfield","lat":50.701698,"long":23.204399},{"icao":"NZCH","type":"large_airport","name":"Christchurch International Airport","lat":-43.489398956299,"long":172.53199768066},{"icao":"EDDM","type":"large_airport","name":"Munich Airport","lat":48.353802,"long":11.7861},{"icao":"EGPD","type":"medium_airport","name":"Aberdeen Dyce Airport","lat":57.2019,"long":-2.19778},{"icao":"CYYC","type":"large_airport","name":"Calgary International Airport","lat":51.113899231,"long":-114.019996643},{"icao":"VNLK","type":"small_airport","name":"Lukla Airport","lat":27.686899185181,"long":86.729698181152},{"icao":"EHAM","type":"large_airport","name":"Amsterdam Airport Schiphol","lat":52.308601,"long":4.76389},{"icao":"LSZO","type":"small_airport","name":"Flugplatz Berom\u00fcnster","lat":47.189999,"long":8.20472},{"icao":"KSAN","type":"large_airport","name":"San Diego International Airport","lat":32.7336006165,"long":-117.190002441},{"icao":"YMML","type":"large_airport","name":"Melbourne International Airport","lat":-37.673302,"long":144.843002},{"icao":"LIPD","type":"small_airport","name":"Udine-Campoformido Air Base","lat":46.0322,"long":13.1868},{"icao":"LIDK","type":"heliport","name":"Casarsa della Delizia Air Base","lat":45.953167,"long":12.816717},{"icao":"PAHV","type":"small_airport","name":"Healy River Airport","lat":63.866199493408,"long":-148.96899414062},{"icao":"PACY","type":"small_airport","name":"Yakataga Airport","lat":60.080974,"long":-142.494541},{"icao":"PAVD","type":"medium_airport","name":"Valdez Pioneer Field","lat":61.1339,"long":-146.248001},{"icao":"MPTO","type":"large_airport","name":"Tocumen International Airport","lat":9.0713596344,"long":-79.3
